"""default requirements for matter

Revision ID: d687bd85b9d6
Revises: d796882ee884
Create Date: 2026-02-02 07:42:00.044023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from squola.models import EnumArray, MatterRequirements


# revision identifiers, used by Alembic.
revision: str = 'd687bd85b9d6'
down_revision: Union[str, Sequence[str], None] = 'd796882ee884'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matters', sa.Column('default_requirements', EnumArray(MatterRequirements), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matters', 'default_requirements')
    # ### end Alembic commands ###
