"""init

Revision ID: d796882ee884
Revises: 
Create Date: 2026-02-01 23:26:30.881027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from squola.models import EnumArray, MatterRequirements


# revision identifiers, used by Alembic.
revision: str = 'd796882ee884'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('class_matter_assignments', sa.Column('requirements', EnumArray(MatterRequirements), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('class_matter_assignments', 'requirements')
    # ### end Alembic commands ###
