name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: raspberrypi

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy stack
        run: docker compose up --build --detach
